server.address=0.0.0.0
server.port=8081
server.http2.enabled=true
spring.main.allow-bean-definition-overriding=true
server.jetty.threads.max=500
server.jetty.threads.min=500

# MongoDB properties
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=online-shop

# Tiny event sourcing library properties
event.sourcing.auto-scan-enabled=true
event.sourcing.scan-package=ru.quipy
event.sourcing.snapshots-enabled=false
event.sourcing.sagas-enabled=false

# Postgres event store properties
spring.datasource.url=jdbc:postgresql://${POSTGRES_ADDRESS:localhost}:${POSTGRES_PORT:65432}/postgres
spring.datasource.username=tiny_es
spring.datasource.password=tiny_es
spring.datasource.hikari.maximum-pool-size=500
spring.datasource.hikari.minimum-idle=500

management.metrics.web.server.request.autotime.percentiles=0.95
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=info,health,prometheus,metrics

payment.service-name=${PAYMENT_SERVICE_NAME}
payment.token=${PAYMENT_TOKEN}
payment.accounts=acc-13
payment.hostPort=${PAYMENT_HOST:localhost}:${PAYMENT_PORT:1234}